# Input topics handled/muxed.
# For each topic:
# - name: name identifier to select the topic
# - topic   : input topic of geometry_msgs::Twist type
# - timeout : timeout in seconds to start discarding old messages, and use 0.0 speed instead
# - priority: priority in the range [0, 255]; the higher the more priority over other topics
/**:
  ros__parameters:

    # Publishing rate
    rate: 30.0

    # the size of the message queue for pose and scan topics
    queue_size: 20

    # Timeout for pose and scan synchronization
    timeout: 0.04

